global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # If using Docker service name

  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['10.171.221.161:8080']  # ✅ Jenkins machine IP address

